import {View, Text, Image, TouchableOpacity,StyleSheet} from 'react-native';
import React from 'react';
import {colors} from '../constant';

const SplashScreen = ({navigation}) => {
  return (
    <View style={{marginTop: 40}}>
      <View
        style={styles.topContainer}>
        <Image
          source={require('../assets/Vector.png')}
          style={{height: 35, width: 40}}
        />
        <Text
          style={
            styles.consultTxt
          }>
          CONSULT
        </Text>
      </View>
      <View
        style={{justifyContent: 'center', marginHorizontal: 30, marginTop: 100}}>
        <Image
          source={require('../assets/welcom_img.png')}
          style={{height: 200, width: 275}}
        />
        <Text
          style={
            styles.text2
          }>
          Consult Specialist Doctors For Your Better Treatment{' '}
        </Text>
        <Text
          style={{
            color: colors.textColor,
            fontSize: 15,
            fontWeight: '300',
            alignSelf: 'center',
            marginTop: 20,
            textAlign: 'center',
          }}>
          A consultation note is generated by a provider upon request for an
          opinion or advice from another provider.{' '}
        </Text>
      </View>
      <TouchableOpacity style = {
        styles.startBtn
      }
      activeOpacity={0.8}
      onPress={()=>navigation.navigate('SignUp')}
      >
        <Text style={{
            color:colors.white,
            fontWeight:'600',
            fontSize:20
        }}>Let's Start</Text>
      </TouchableOpacity>
      <Text
          style={{
            color: colors.textColor,
            fontSize: 15,
            fontWeight: '600',
            alignSelf: 'center',
            marginTop: 120,
            textAlign: 'center',

          }}>
        Made by Yash
        </Text>
    </View>
  );
};

const styles = StyleSheet.create({
    topContainer:{
        marginHorizontal: 50,
          flexDirection: 'row',
          justifyContent: 'center'
    },
    consultTxt:{
        color: colors.primaryColor,
            fontSize: 16,
            fontWeight: '900',
            alignSelf: 'center',
            margin: 10,
    },
    text2:{
        color: colors.primaryColor,
            fontSize: 16,
            fontWeight: '600',
            alignSelf: 'center',
            marginTop: 40,
            textAlign: 'center',
    },
    startBtn:{
        alignSelf:'center',
        justifyContent:'center',
        alignItems:'center',
        marginTop:60,
        height:40,
        width:160,
        backgroundColor:colors.primaryColor,
        borderRadius:10,
    }
    
})

export default SplashScreen;
